{% set name = "streamlit-bokeh-events" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/streamlit-bokeh-events-{{ version }}.tar.gz
  sha256: 47914b7778ac7ff56f34f3fedc2bb947fb7fcdad10c8187996d4a02c5f711e59

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - bokeh >=2.0.0
    - python >={{ python_min }}
    - streamlit >=0.63

test:
  imports:
    - streamlit_bokeh_events
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ash2shukla/streamlit-bokeh-events/
  summary: A custom streamlit component to return js event values from bokeh plots to streamlit
  license_file: LICENSE.txt
  license: MIT 

extra:
  recipe-maintainers:
    - omics-tools
